#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
cd "$ROOT"

go_bin="${GO:-go}"

"$go_bin" fmt ./...
"$go_bin" vet ./...
"$go_bin" test ./...
"$go_bin" test -race ./...

